#One-way ANOVA
Air=filter(US_Supply_Chain,Shipping_Mode=="Air")
Rail=filter(US_Supply_Chain,Shipping_Mode=="Rail")
Road=filter(US_Supply_Chain,Shipping_Mode=="Road")
Sea=filter(US_Supply_Chain,Shipping_Mode=="Sea")
shapiro.test(Air$Energy_Consumption_Joules)
shapiro.test(Rail$Energy_Consumption_Joules)
shapiro.test(Road$Energy_Consumption_Joules)
shapiro.test(Sea$Energy_Consumption_Joules)
Air$log10_Energy_Consumption_Joules<- log(Air$Energy_Consumption_Joules, base = 10)
Rail$log10_Energy_Consumption_Joules<- log(Rail$Energy_Consumption_Joules, base = 10)
Road$log10_Energy_Consumption_Joules<- log(Road$Energy_Consumption_Joules, base = 10)
Sea$log10_Energy_Consumption_Joules<- log(Sea$Energy_Consumption_Joules, base = 10)
shapiro.test(Air$log10_Energy_Consumption_Joules)
shapiro.test(Rail$log10_Energy_Consumption_Joules)
shapiro.test(Road$log10_Energy_Consumption_Joules)
shapiro.test(Sea$log10_Energy_Consumption_Joules)
leveneTest(Energy_Consumption_Joules ~ as.factor(Shipping_Mode), data = US_Supply_Chain)
ShippingMode_Anova<-aov(Energy_Consumption_Joules ~ as.factor(Shipping_Mode), data = US_Supply_Chain)
summary(ShippingMode_Anova)
TukeyHSD(ShippingMode_Anova)
plot(ShippingMode_Anova, 1)
