Low_risk=filter(US_Supply_Chain,Supply_Risk_Flag=="0")
High_risk=filter(US_Supply_Chain,Supply_Risk_Flag=="1")
shapiro.test(Low_risk$Supplier_Reliability_Score)
shapiro.test(High_risk$Supplier_Reliability_Score)
Low_risk$log10_Supplier_Reliability_Score <- log(Low_risk$Supplier_Reliability_Score, base = 10)
High_risk$log10_Supplier_Reliability_Score <- log(High_risk$Supplier_Reliability_Score, base = 10)
shapiro.test(Low_risk$log10_Supplier_Reliability_Score)
shapiro.test(High_risk$log10_Supplier_Reliability_Score)
leveneTest(Supplier_Reliability_Score ~ as.factor(Supply_Risk_Flag), data = US_Supply_Chain)
t.test(Supplier_Reliability_Score ~ as.factor(Supply_Risk_Flag),data = US_Supply_Chain,alternative="greater",var.equal = TRUE)
