library(tidyverse)
library(dplyr)
library(car)
library(WRS2)
library(onewaytests)
library(lmPerm)
getwd()
setwd("/Users/gayathrigmenon/Desktop/Fall\'25/MIS\ 7700\ Data\ Analytics/mid\ term\ Project")
df <- read_csv("US Supply Chain.csv") %>%
  filter(Shipping_Mode %in% c("Air", "Road", "Rail"),Disruption_Severity %in% c("Low","High")) %>%
  mutate(Shipping_Mode = as.factor(Shipping_Mode),Disruption_Severity = as.factor(Disruption_Severity))
Air=filter(df,Shipping_Mode=="Air")
Rail=filter(df,Shipping_Mode=="Rail")
Road=filter(df,Shipping_Mode=="Road")
shapiro.test(Air$Energy_Consumption_Joules)
shapiro.test(Rail$Energy_Consumption_Joules)
shapiro.test(Road$Energy_Consumption_Joules)
Air$log10_Energy_Consumption_Joules<- log(Air$Energy_Consumption_Joules, base = 10)
Rail$log10_Energy_Consumption_Joules<- log(Rail$Energy_Consumption_Joules, base = 10)
Road$log10_Energy_Consumption_Joules<- log(Road$Energy_Consumption_Joules, base = 10)
shapiro.test(Air$log10_Energy_Consumption_Joules)
shapiro.test(Rail$log10_Energy_Consumption_Joules)
shapiro.test(Road$log10_Energy_Consumption_Joules)

leveneTest(Energy_Consumption_Joules ~ Shipping_Mode * Disruption_Severity, data = df)
model <- aov(Energy_Consumption_Joules ~ Shipping_Mode * Disruption_Severity, data = df)
summary(model)
t2way(Energy_Consumption_Joules ~ Shipping_Mode * Disruption_Severity, data = df)
tukey_results <- TukeyHSD(model)
tukey_results
plot(tukey_results, las = 1, col = "green")